# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_url', models.CharField(max_length=60)),
                ('note_title', models.CharField(max_length=100)),
                ('note_text', models.CharField(max_length=600)),
                ('note_tags', models.CharField(max_length=150)),
                ('note_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'note',
            },
        ),
    ]
