# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20170306_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_userid', models.CharField(max_length=20)),
                ('shorten_url', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'noteshareobj',
            },
        ),
    ]
